plugins:
  etcd:
    executor: central_deployment_agent
    package_name: cloudify-etcd-plugin
    package_version: '1.0.0'

dsl_definitions:
  client_config: &client_config
    client_config:
      type: cloudify.datatypes.etcd.ClientConfig
      description: Etcd key-value store client configuration.
      required: true

data_types:

  cloudify.datatypes.etcd.ClientConfig:
    properties:
      host:
        type: string
        default: localhost
      port:
        type: integer
        default: 2379
      user:
        type: string
        required: false
      password:
        type: string
        required: false
      ca_cert:
        type: string
        required: false
      cert_key:
        type: string
        required: false
      cert_cert:
        type: string
        required: false
      timeout:
        type: integer
        required: false
      grpc_options:
        required: false
        default: {}
      kwargs:
        description: >
          A dictionary of keys and values that is not validated
          but will override other values in the client config.
        default: {}

  cloudify.datatypes.etcd.resourceconfig.KeyValuePair:
    properties:
      key:
        description: The key of the key-value pair.
        type: string
        required: true
      value:
        description: The key of the key-value pair.
        type: string
        required: true


node_types:

  cloudify.nodes.etcd.Base:
    derived_from: cloudify.nodes.Compute
    properties:
      <<: *client_config

  cloudify.nodes.etcd.KeyValuePair:
    derived_from: cloudify.nodes.etcd.Base
    properties:
      resource_config:
        type: cloudify.datatypes.etcd.resourceconfig.KeyValuePair
        required: true
      use_existing_resource:
        description: Whether to create new resource or fetch existing
        default: false
    # interfaces:
    #   cloudify.interfaces.lifecycle:
    #     create: etcd.etcd_plugin.keyvaluepair.create
    #     delete: etcd.etcd_plugin.keyvaluepair.delete
