plugins:
  etcd:
    executor: central_deployment_agent
    package_name: cloudify-etcd-plugin
    package_version: '1.0.0'

dsl_definitions:
  client_config: &client_config
    client_config:
      type: cloudify.types.etcd.ClientConfig
      description: Etcd key-value store client configuration.
      required: false

data_types:

  cloudify.types.etcd.ClientConfig:
    properties:
      host:
        type: string
        default: localhost
      port:
        type: integer
        default: 2379
      user:
        type: string
        required: false
      password:
        type: string
        required: false
      ca_cert:
        type: string
        required: false
      cert_key:
        type: string
        required: false
      cert_cert:
        type: string
        required: false
      timeout:
        type: integer
        required: false
      grpc_options:
        required: false
        default: {}
      kwargs:
        description: >
          A dictionary of keys and values that is not validated
          but will override other values in the client config.
        default: {}

node_types:

  cloudify.nodes.openstack.NetworkBase:
    derived_from: cloudify.nodes.Network
    properties:
      <<: *external_resource
      <<: *create_if_missing
      <<: *client_config

