plugins:
  etcd:
    executor: central_deployment_agent
    package_name: cloudify-etcd-plugin
    package_version: '1.0.0'

dsl_definitions:
  client_config: &client_config
    client_config:
      type: cloudify.datatypes.etcd.ClientConfig
      description: Etcd key-value store client configuration.
      required: true

  external_resource: &external_resource
    use_external_resource:
      description: Indicate whether the resource exists or if Cloudify should create the resource, true if you are bringing an existing resource, false if you want cloudify to create it.
      type: boolean
      default: false

  create_if_missing: &create_if_missing
    create_if_missing:
      type: boolean
      default: false
      description: If use_external_resource is ``true`` and the resource is missing,create it instead of failing.

data_types:

  cloudify.datatypes.etcd.ClientConfig:
    properties:
      host:
        type: string
        default: localhost
      port:
        type: integer
        default: 2379
      user:
        type: string
        required: false
      password:
        type: string
        required: false
      ca_cert:
        type: string
        required: false
      cert_key:
        type: string
        required: false
      cert_cert:
        type: string
        required: false
      timeout:
        type: integer
        required: false
      grpc_options:
        required: false

  cloudify.datatypes.etcd.resourceconfig.KeyValuePair:
    properties:
      key:
        description: The key of the key-value pair.
        type: string
        required: true
      value:
        description: The value of the key-value pair.
        type: string
        required: true
      lease:
        description: >
          All keys attached to this lease will be expired and deleted if
          the lease expires.
        required: false
      fail_on_overwrite:
        description: Fail and prevent from overwriting existing value.
        type: boolean
        required: false

  cloudify.datatypes.etcd.resourceconfig.WatchKey:
    properties:
      key:
        description: The key to watch.
        type: string
        required: true
      condition:
        description: >
          A string that stops watching the key once it is encountered.
        type: string
        required: true
      timeout:
        description: >
          Maximum waiting time in seconds until condition (default is 10 minutes).
        type: integer
        required: false

  cloudify.datatypes.etcd.resourceconfig.Lock:
    properties:
      lock_name:
        description: >
          The identifier for the distributed shared lock to be acquired.
        type: string
        required: true
      ttl:
        description: >
          The length of time for the lock to live for in seconds (default
          is 60 seconds). The lock will be released after this time elapses,
          unless refreshed.
        type: integer
        required: false
      acquire_timeout:
        description: >
          The timeout in seconds on acquiring lock (default is 10 seconds).
        type: integer
        required: false

  cloudify.datatypes.etcd.resourceconfig.Member:
    properties:
      peer_urls:
        description: >
          The list of one or more peer URLs, eg. http://127.0.0.1:2380.
        type: list
        required: true


node_types:

  cloudify.nodes.etcd.Base:
    derived_from: cloudify.nodes.Root
    properties:
      <<: *client_config

  cloudify.nodes.etcd.KeyValuePair:
    derived_from: cloudify.nodes.etcd.Base
    properties:
      <<: *external_resource
      <<: *create_if_missing
      resource_config:
        type: cloudify.datatypes.etcd.resourceconfig.KeyValuePair
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create: etcd.etcd_plugin.keyvaluepair.create
        delete: etcd.etcd_plugin.keyvaluepair.delete

  cloudify.nodes.etcd.KeyValuePairs:
    derived_from: cloudify.nodes.etcd.Base
    properties:
      <<: *external_resource
      <<: *create_if_missing
      resource_config:
        type: list
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create: etcd.etcd_plugin.keyvaluepairs.create
        delete: etcd.etcd_plugin.keyvaluepairs.delete

  cloudify.nodes.etcd.WatchKey:
    derived_from: cloudify.nodes.etcd.Base
    properties:
      resource_config:
        type: cloudify.datatypes.etcd.resourceconfig.WatchKey
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create: etcd.etcd_plugin.watchkey.watch
        delete: etcd.etcd_plugin.watchkey.delete

  cloudify.nodes.etcd.Lock:
    derived_from: cloudify.nodes.etcd.Base
    properties:
      resource_config:
        type: cloudify.datatypes.etcd.resourceconfig.Lock
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create: etcd.etcd_plugin.lock.create
        refresh: etcd.etcd_plugin.lock.refresh
        delete: etcd.etcd_plugin.lock.delete

  cloudify.nodes.etcd.Member:
    derived_from: cloudify.nodes.etcd.Base
    properties:
      resource_config:
        type: cloudify.datatypes.etcd.resourceconfig.Member
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create: etcd.etcd_plugin.member.create
        delete: etcd.etcd_plugin.member.delete
      cloudify.interfaces.operations:
        update: etcd.etcd_plugin.member.update
        disarm: etcd.etcd_plugin.member.disarm
