rest_calls:
  - path: /v1/tenants/162187389399964099750194888486389256873/services/flexvnf/nf/versa_flexvnf_ucpe1/config
    # TODO: check the path, use parameters
    method: POST
    headers:
      Content-type: application/json
      Authorization: 'Bearer {{versa_flexvnf_token}}'
    raw_payload: templates/versa-post-pipeline-nf-config.json
    payload_format: raw
    response_format: json
    recoverable_codes: [400]
    response_translation:
      pipeline_nf_config: [pipeline_nf_config]
