rest_calls:
  - path: /v1/tenants/75577886618737682833000713979859424131/services/flexvnf/nf/versa_flexvnf_ucpe1/config
    method: POST
    headers:
      Content-type: application/json
      Authorization: 'Bearer {{nefeli_token}}'
    raw_payload: templates/versa-post-pipeline-nf-config.json
    payload_format: raw
    response_format: json
    recoverable_codes: [400]
    response_translation:
      pipeline_nf_config: [pipeline_nf_config]
