rest_calls:
  - path: /v1/tenants/75577886618737682833000713979859424131/services/flexvnf/nf/versa_flexvnf_file/config
    # TODO: check the path, use parameters
    method: POST
    headers:
      Content-type: application/json
      Authorization: 'Bearer {{nefeli_token}}'
    raw_payload: templates/versa-post-pipeline-nf-config.json
    payload_format: raw
    response_format: json
